services:
  # A service named 'webserver'
  webserver:
    # Specifies the image to use, including a tag (e.g., :latest, :alpine)
    image: my-django-app
    ports:
      # Maps host port 80 to container port 80
      - "8000:8000"
    restart: unless-stopped